name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/*.gitattributes"
      - "**/*.gitignore"
      - "**/*.md"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork == false || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application
        run: echo "Building application..."

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA environment..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-qa
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment..."

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production  # Links to the 'production' environment
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
