
name: CI/CD Pipeline

on:
  # Trigger on PR creation or when code is pushed to 'main'
  pull_request:
  push:
    branches:
      - main

  # Manual trigger for production deployment
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build application
        run: echo "Building application..."

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA environment..."

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-qa
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging environment..."

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    # Manual trigger required for this job
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production environment..."
