name: Deploy Action

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
    deploy-step-1:
      name: Deploy Step 1 - ${{ inputs.environment }}
      runs-on: ubuntu-latest
      concurrency:
        # group: deploy-step-1-lock
        # cancel-in-progress: false  # ⬅ Ensures jobs WAIT instead of being canceled
        group: deploy-step-1-${{ github.ref }}
        cancel-in-progress: true
      steps:
        - name: Deploy Step 1
          run: echo "Running Step 1 for ${{ inputs.environment }}"

#   deploy-step-2:
#     name: Deploy Step 2 - ${{ inputs.environment }}  # Dynamic name
#     runs-on: ubuntu-latest
#     needs: deploy-step-1
#     steps:
#       - name: Deploy Step 2
#         run: echo "Running Step 2 for ${{ inputs.environment }}"

#   deploy-step-3:
#     name: Deploy Step 3 - ${{ inputs.environment }}  # Dynamic name
#     runs-on: ubuntu-latest
#     needs: deploy-step-2
#     steps:
#       - name: Deploy Step 3
#         run: echo "Running Step 3 for ${{ inputs.environment }}"
